src/routes/dashboard.py
from flask import Blueprint, request
from src.views.dashboard_controller import add_field_view, map_view, fields_view
from flask_login import login_required

dashboard_route = Blueprint('dashboard_route', __name__, url_prefix='/dashboard')

@dashboard_route.route('/map')
# @login_required
def show_map():
    return map_view()

@dashboard_route.route('/fields')
def show_fields():
    return fields_view()

@dashboard_route.route('/fields/add-field')
def add_field():
    return add_field_view()

src/routes/polygon.py
from flask import Blueprint, jsonify, request, abort, send_from_directory
from flask_login import current_user
from src.models.polygon import Polygon
import json
import datetime
from geoalchemy2 import functions, elements
import matplotlib
import matplotlib.pyplot as plt
matplotlib.use('Agg')
from matplotlib.patches import Polygon as MT_Polygon
from src.utils.extensions import db
from sqlalchemy import text
from shapely.geometry import shape, Polygon as Poly

polygon_route = Blueprint('polygon_route', __name__, url_prefix='/api/polygon')

def draw_polygon_coordinates(coordinates, file_name):
    print(coordinates)
    
    # PNG fayl nomini o'zgartiring
    output_file = f"src/uploads/{file_name}.png"
    
    fig, ax = plt.subplots()
    polygon = MT_Polygon(coordinates,edgecolor='black',
                #  facecolor=None,
                 color='#38d9a9',
                 linewidth=None,
                 linestyle=None,
                 antialiased=None,
                 hatch=None,
                 
                 joinstyle=None,)
    ax.add_patch(polygon)
    ax.autoscale_view()

    # PNG rasmni saqlash
    plt.axis('off')
    plt.style.use('classic')
    plt.savefig(output_file, format='png', bbox_inches="tight", pad_inches = 0, transparent=True)
    plt.close(fig)

@polygon_route.route('/save', methods=['GET', 'POST'])
def polygon_save():
    if request.method == 'POST':
        req_data = request.get_json()
        print('req_data : ', req_data)
        place_name = req_data['field_name']
        crop_code = req_data['crop_code']
        place_area = req_data['field_area']
        place_length = req_data['field_length']
        geometry = req_data['geometry']
        
        if geometry['type'] == 'Polygon':
            geometry['coordinates'] = [geometry['coordinates']]
            geometry['type'] = 'MultiPolygon'
            
        polygon = Polygon.create(user_id=current_user.id, place_name=place_name, crop_code=crop_code, place_area=place_area, place_length=place_length, geometry=json.dumps(geometry))
        
        draw_polygon_coordinates(geometry['coordinates'][0][0], polygon.id)
        
        obj = {
            "success": True, 
            "polygon_id" : polygon.id,
            "place_name" : polygon.place_name,
            "crop_name" : polygon.crop_code,
            "place_area" : polygon.place_area,
            "place_length" : polygon.place_length
        }
    return jsonify(obj)


@polygon_route.route('/get', methods=['GET', 'POST'])
def get_polygon():
    data = Polygon.get()
    return jsonify(data)


@polygon_route.route('/get/<int:field_id>', methods=['GET', 'POST'])
def get_info_polygon(field_id):
    field = db.session.query(Polygon).filter_by(id=field_id).first()
    field_obj = {
        "place_name" : field.place_name,
        "crop_code" : field.crop_code,
        "id" : field.id
    }
    return jsonify(field_obj)


@polygon_route.route('/<int:poly_id>/image', methods=['GET', 'POST'])
def get_polygon_image(poly_id):
    return send_from_directory("uploads", f"{poly_id}.png")

    
@polygon_route.route('/draw', methods=['GET', 'POST'])
def polygon_draw():
    if request.method == 'POST':
        req_data = request.get_json()
        geometry = req_data['geometry']
        print(geometry)
        if geometry['type'] == 'Polygon':
            geometry['coordinates'] = [geometry['coordinates']]
            geometry['type'] = 'MultiPolygon'
        elif geometry['type'] == 'LineString':
            pass
        
        current_time = datetime.datetime.now()
        image_id = f"{current_time.minute}{current_time.second}{current_time.microsecond}"
        draw_polygon_coordinates(geometry['coordinates'][0][0], image_id)
        return jsonify(image_id)


@polygon_route.route('/area', methods=['GET', 'POST'])
def get_polygon_area():
    if request.method == 'POST':
        coordinates = request.get_json()
        field_area = db.session.query(functions.ST_Area(functions.ST_GeomFromGeoJSON(json.dumps({
                        "type": "MultiPolygon",
                        "coordinates": [coordinates]
                     }))) ).first()[0] * 1000000
        
        # field_perimeter = db.session.query(functions.ST_Perimeter(functions.ST_GeomFromGeoJSON(json.dumps({
        #                 "type": "MultiPolygon",
        #                 "coordinates": [coordinates]
        #              }))) ).first()[0] * 100000
        polygon = Poly(coordinates[0])
        wkt_polygon = f"POLYGON ({', '.join([f'{lon} {lat}' for lon, lat in coordinates[0]])})"
        geo_polygon  = functions.ST_GeomFromText(wkt_polygon)
        # field_perimeter = functions.ST_Perimeter(geo_polygon)
        print(polygon)
        print(wkt_polygon)
        print(geo_polygon)
        print(functions.ST_AsText(polygon))
        return jsonify(field_area)
    

@polygon_route.route('/update/<int:field_id>', methods=['PUT'])
def update_polygon(field_id):
    if request.method == 'PUT':
        req_data = request.get_json()
        field = db.session.query(Polygon).filter_by(id=field_id).first()
        field.place_name = req_data['field_name']
        field.crop_code = req_data['crop_code']
        field.place_area = req_data['field_area']        
        field.place_length = req_data['field_length']        
        
        geometry = req_data['geometry']
        if geometry['type'] == 'Polygon':
            geometry['coordinates'] = [geometry['coordinates']]
            geometry['type'] = 'MultiPolygon'
        
        geometry = shape(geometry)
        field.geometry = elements.WKBElement(geometry.wkb, srid=4326)
        db.session.commit()
        return jsonify('Polygon updated')


@polygon_route.route('/delete/<int:field_id>')
def delete_polygon(field_id):
    deletable_polygon = db.session.query(Polygon).filter_by(id=field_id).first()
    db.session.delete(deletable_polygon)
    db.session.commit()
    return jsonify('Polygon deleted')



# @polygon_route.route('/perimeter')

# @polygon_route.route('/perimeter', methods=['GET', 'POST'])
# def get_polygon_area():
#     if request.method == 'POST':
#         coordinates = request.get_json()
#         field_perimeter = db.session.query(functions.ST_Perimeter(functions.ST_GeomFromGeoJSON(json.dumps({
#                         "type": "MultiPolygon",
#                         "coordinates": [coordinates]
#                      }))) ).first()[0] * 1000000
#         return jsonify(field_perimeter)

src/templates/add.field.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/normalize.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/dashboard.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/responsive.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/map.css') }}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>

    <!-- LEAFLET -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
        integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
        integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
    <!-- LEAFLET GEOMAN -->
    <link rel="stylesheet" href="https://unpkg.com/@geoman-io/leaflet-geoman-free@latest/dist/leaflet-geoman.css" />
    <script src="https://unpkg.com/@geoman-io/leaflet-geoman-free@latest/dist/leaflet-geoman.min.js"></script>

    

    <!-- Turf js -->
    <script src='https://unpkg.com/@turf/turf@6/turf.min.js'></script>

    <title>Geo Draw</title>

    <style>
        .crop__dashboard-main {
            width: 100vw;
        }
    </style>

</head>

<body>
    <div class="crop__dashboard">
        <div class="crop__dashboard-inner">
            <main class="crop__dashboard-main">
                <header class="crop__dashboard-header">
                    <h2 class="text-center">Add Field Page</h2>
                </header>
                <div class="crop__dashboard-content">
                    <div class="map__container">
                        <div id="map"></div>
                        <div class="map__actions">
                            <a class="map__close-btn" href="{{ url_for('dashboard_route.show_map') }}">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M13.4099 12.0002L19.7099 5.71019C19.8982 5.52188 20.004 5.26649 20.004 5.00019C20.004 4.73388 19.8982 4.47849 19.7099 4.29019C19.5216 4.10188 19.2662 3.99609 18.9999 3.99609C18.7336 3.99609 18.4782 4.10188 18.2899 4.29019L11.9999 10.5902L5.70994 4.29019C5.52164 4.10188 5.26624 3.99609 4.99994 3.99609C4.73364 3.99609 4.47824 4.10188 4.28994 4.29019C4.10164 4.47849 3.99585 4.73388 3.99585 5.00019C3.99585 5.26649 4.10164 5.52188 4.28994 5.71019L10.5899 12.0002L4.28994 18.2902C4.19621 18.3831 4.12182 18.4937 4.07105 18.6156C4.02028 18.7375 3.99414 18.8682 3.99414 19.0002C3.99414 19.1322 4.02028 19.2629 4.07105 19.3848C4.12182 19.5066 4.19621 19.6172 4.28994 19.7102C4.3829 19.8039 4.4935 19.8783 4.61536 19.9291C4.73722 19.9798 4.86793 20.006 4.99994 20.006C5.13195 20.006 5.26266 19.9798 5.38452 19.9291C5.50638 19.8783 5.61698 19.8039 5.70994 19.7102L11.9999 13.4102L18.2899 19.7102C18.3829 19.8039 18.4935 19.8783 18.6154 19.9291C18.7372 19.9798 18.8679 20.006 18.9999 20.006C19.132 20.006 19.2627 19.9798 19.3845 19.9291C19.5064 19.8783 19.617 19.8039 19.7099 19.7102C19.8037 19.6172 19.8781 19.5066 19.9288 19.3848C19.9796 19.2629 20.0057 19.1322 20.0057 19.0002C20.0057 18.8682 19.9796 18.7375 19.9288 18.6156C19.8781 18.4937 19.8037 18.3831 19.7099 18.2902L13.4099 12.0002Z"
                                        fill="#FCC419" />
                                </svg>
                            </a>
                            <button class="map__delete-btn">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M20 6H16V5C16 4.20435 15.6839 3.44129 15.1213 2.87868C14.5587 2.31607 13.7956 2 13 2H11C10.2044 2 9.44129 2.31607 8.87868 2.87868C8.31607 3.44129 8 4.20435 8 5V6H4C3.73478 6 3.48043 6.10536 3.29289 6.29289C3.10536 6.48043 3 6.73478 3 7C3 7.26522 3.10536 7.51957 3.29289 7.70711C3.48043 7.89464 3.73478 8 4 8H5V19C5 19.7956 5.31607 20.5587 5.87868 21.1213C6.44129 21.6839 7.20435 22 8 22H16C16.7956 22 17.5587 21.6839 18.1213 21.1213C18.6839 20.5587 19 19.7956 19 19V8H20C20.2652 8 20.5196 7.89464 20.7071 7.70711C20.8946 7.51957 21 7.26522 21 7C21 6.73478 20.8946 6.48043 20.7071 6.29289C20.5196 6.10536 20.2652 6 20 6ZM10 5C10 4.73478 10.1054 4.48043 10.2929 4.29289C10.4804 4.10536 10.7348 4 11 4H13C13.2652 4 13.5196 4.10536 13.7071 4.29289C13.8946 4.48043 14 4.73478 14 5V6H10V5ZM17 19C17 19.2652 16.8946 19.5196 16.7071 19.7071C16.5196 19.8946 16.2652 20 16 20H8C7.73478 20 7.48043 19.8946 7.29289 19.7071C7.10536 19.5196 7 19.2652 7 19V8H17V19Z"
                                        fill="#F03E3E" />
                                </svg>
                            </button>
                            <button class="map__addPerm-btn">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M18.7099 7.20986C18.617 7.11613 18.5064 7.04174 18.3845 6.99097C18.2627 6.9402 18.132 6.91406 17.9999 6.91406C17.8679 6.91406 17.7372 6.9402 17.6154 6.99097C17.4935 7.04174 17.3829 7.11613 17.29 7.20986L9.83995 14.6699L6.70995 11.5299C6.61343 11.4366 6.49949 11.3633 6.37463 11.3141C6.24978 11.2649 6.11645 11.2408 5.98227 11.2431C5.84809 11.2454 5.71568 11.2741 5.5926 11.3276C5.46953 11.3811 5.35819 11.4583 5.26495 11.5549C5.17171 11.6514 5.0984 11.7653 5.04919 11.8902C4.99999 12.015 4.97586 12.1484 4.97818 12.2825C4.9805 12.4167 5.00923 12.5491 5.06272 12.6722C5.11622 12.7953 5.19343 12.9066 5.28995 12.9999L9.12995 16.8399C9.22291 16.9336 9.33351 17.008 9.45537 17.0588C9.57723 17.1095 9.70794 17.1357 9.83995 17.1357C9.97196 17.1357 10.1027 17.1095 10.2245 17.0588C10.3464 17.008 10.457 16.9336 10.55 16.8399L18.7099 8.67986C18.8115 8.58622 18.8925 8.47257 18.9479 8.34607C19.0033 8.21957 19.0319 8.08296 19.0319 7.94486C19.0319 7.80676 19.0033 7.67015 18.9479 7.54365C18.8925 7.41715 18.8115 7.3035 18.7099 7.20986Z"
                                        fill="#20C997" />
                                </svg>
                            </button>
                            <button class="map__draw-btn">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M22 7.24002C22.0008 7.10841 21.9756 6.97795 21.9258 6.85611C21.876 6.73427 21.8027 6.62346 21.71 6.53002L17.47 2.29002C17.3766 2.19734 17.2658 2.12401 17.1439 2.07425C17.0221 2.02448 16.8916 1.99926 16.76 2.00002C16.6284 1.99926 16.4979 2.02448 16.3761 2.07425C16.2543 2.12401 16.1435 2.19734 16.05 2.29002L13.22 5.12002L2.29002 16.05C2.19734 16.1435 2.12401 16.2543 2.07425 16.3761C2.02448 16.4979 1.99926 16.6284 2.00002 16.76V21C2.00002 21.2652 2.10537 21.5196 2.29291 21.7071C2.48045 21.8947 2.7348 22 3.00002 22H7.24002C7.37994 22.0076 7.51991 21.9857 7.65084 21.9358C7.78176 21.8858 7.90073 21.8089 8.00002 21.71L18.87 10.78L21.71 8.00002C21.8013 7.9031 21.8757 7.79155 21.93 7.67002C21.9397 7.59031 21.9397 7.50973 21.93 7.43002C21.9347 7.38347 21.9347 7.33657 21.93 7.29002L22 7.24002ZM6.83002 20H4.00002V17.17L13.93 7.24002L16.76 10.07L6.83002 20ZM18.17 8.66002L15.34 5.83002L16.76 4.42002L19.58 7.24002L18.17 8.66002Z"
                                        fill="#38D9A9" />
                                </svg>

                            </button>
                        </div>
                        <div class="field__add-leftSide">
                            <form class="field__add-form h-100 d-block" id="field__form">
                                <legend class="field__legend text-center">Add Field</legend>
                                <div class="mb-3">
                                    <div class="field__image-wrapper d-flex flex-column align-items-center">

                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label for="fieldName" class="form-label">Field Name</label>
                                    <input type="text" class="form-control" id="fieldName" name="field_name" value="Field name">
                                </div>
                                <div class="mb-3">
                                    <select class="form-select" name="crop_name" aria-label="Default select example">
                                        <option hidden selected disabled>Crop name</option>
                                        <option value="1">Paxta</option>
                                        <option value="2">Bug`doy</option>
                                        <option value="3">No`xat</option>
                                        <option value="4">Piyoz</option>
                                    </select>
                                </div>
                                <div class="field__actions mb-3 d-flex flex-column">
                                    <button type="submit" class="field__form-add btn btn-primary mb-2">Save</button>
                                    <button type="button" class="field__form-cancel btn btn-secondary">Cancel</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>


    <script src="{{ url_for('static', filename='scripts/map.utils.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/map.js') }}"></script>
    <script>
        let polyImageUrl = "{{ url_for('polygon_route.get_polygon_image', poly_id=-1) }}"
    </script>
    <script>
        map.pm.addControls(controls);
        map.pm.enableDraw("Polygon")
    </script>
    
</body>

</html>

src/templates/fields.html
{% extends 'layouts/dashboard.base.html' %}

{% block link %}
<!-- LEAFLET -->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
<!-- LEAFLET GEOMAN -->
<link rel="stylesheet" href="https://unpkg.com/@geoman-io/leaflet-geoman-free@latest/dist/leaflet-geoman.css"/>
<script src="https://unpkg.com/@geoman-io/leaflet-geoman-free@latest/dist/leaflet-geoman.min.js"></script>
{% endblock %}

{% block dashboard_content %}
    <!-- <div id="map"></div> -->
    <div>FIELDS</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='scripts/control.js') }}"></script>
<script src="{{ url_for('static', filename='scripts/map.js') }}"></script>
{% endblock %}

src/templates/index.html
{% extends 'layouts/base.html' %}

{% block content %}
    <h1>Hello World!</h1>
{% endblock %}

src/templates/layer_panel.html
{% if current_page=='fields' %}
<div class="crop__dashboard-panel__container map__panel">
    <h3 class="map__panel-title">НАСТРОЙКА ОТОБРАЖЕНИЯ КАРТЫ</h3>
    <div class="map__panel-mapOptions__layer row">
        <span class="map__panel-mapOptions__layerItem col-6">
            <label>
                <input type="radio" name="layers" value="mapbox" checked>
                <img src="../../static/images/mapbox-satellite.png" alt="mapbox-satellite" width="100" height="100">
                <div class="fqa-mapOptions-layerLabel">Mapbox</div>
            </label>
        </span>
        <span class="map__panel-mapOptions__layerItem col-6">
            <label>
                <input type="radio" name="layers" value="osm">
                <img src="../../static/images/osm-satellite.png" alt="osm-satellite" width="100" height="100">
                <div class="fqa-mapOptions-layerLabel"> OSM</div>
            </label>
        </span>
    </div>
    <div class="map__panel-mapOptions__layer row">
        <span class="map__panel-mapOptions__layerItem col-6">
            <label>
                <input type="radio" name="layers" value="google">
                <img src="../../static/images/google-satellite.png" alt="google-satellite" width="100" height="100">
                <div class="fqa-mapOptions-layerLabel">Спутник Google</div>
            </label>
        </span>
        <span class="map__panel-mapOptions__layerItem col-6" style="display: none;">
            <label>
                <input type="radio" name="layers" value="dark">
                <img src="../../static/images/dark-satellite.png" alt="dark-satellite" width="100" height="100">
                <div class="fqa-mapOptions-layerLabel">Темное полотно</div>
            </label>
        </span>
    </div>
</div>
{% elif current_page=='map' %}
<div class="crop__dashboard-panel__container fields__panel">
    <div class="fields__panel-inner">
        <header class="fields__panel-header">
            <h3 class="fields__panel-title">Field List</h3>
        </header>
        <section class="fields__panel-content d-flex flex-column">
            <form class="fields__panel-form">
                <div class="mb-3">
                    <input type="text" class="form-control fields__panel-input" oninput="searchFieldName(this.value)"
                        placeholder="Field name">
                </div>
                <div class="fields__panel-checklist row">
                    <div class="mb-3 col-6">
                        <div class="form-check">
                            <input class="form-check-input field__crop-checkbox" type="checkbox"
                                onclick="searchByCropName(this.value)" value="101010000" id="101010000" checked>
                            <label class="form-check-label text-white" for="101010000">
                                Paxta
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input field__crop-checkbox" type="checkbox"
                                onclick="searchByCropName(this.value)" value="102010000" id="102010000" checked>
                            <label class="form-check-label text-white" for="102010000">
                                Bug`doy
                            </label>
                        </div>
                    </div>
                    <div class="mb-3 col-6">
                        <div class="form-check">
                            <input class="form-check-input field__crop-checkbox" type="checkbox"
                                onclick="searchByCropName(this.value)" value="106010000" id="106010000" checked>
                            <label class="form-check-label text-white" for="106010000">
                                No`xat
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input field__crop-checkbox" type="checkbox"
                                onclick="searchByCropName(this.value)" value="104040000" id="104040000" checked>
                            <label class="form-check-label text-white" for="104040000">
                                Piyoz
                            </label>
                        </div>
                    </div>
                </div>
            </form>
            <ul class="fields__panel-list">
                
            </ul>
            <button type="button" class="fields__panel-add__field btn btn-success d-flex justify-content-center mt-auto">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M19 11H13V5C13 4.73478 12.8946 4.48043 12.7071 4.29289C12.5196 4.10536 12.2652 4 12 4C11.7348 4 11.4804 4.10536 11.2929 4.29289C11.1054 4.48043 11 4.73478 11 5V11H5C4.73478 11 4.48043 11.1054 4.29289 11.2929C4.10536 11.4804 4 11.7348 4 12C4 12.2652 4.10536 12.5196 4.29289 12.7071C4.48043 12.8946 4.73478 13 5 13H11V19C11 19.2652 11.1054 19.5196 11.2929 19.7071C11.4804 19.8946 11.7348 20 12 20C12.2652 20 12.5196 19.8946 12.7071 19.7071C12.8946 19.5196 13 19.2652 13 19V13H19C19.2652 13 19.5196 12.8946 19.7071 12.7071C19.8946 12.5196 20 12.2652 20 12C20 11.7348 19.8946 11.4804 19.7071 11.2929C19.5196 11.1054 19.2652 11 19 11Z"
                        fill="white" />
                </svg>
                Add Field
            </button>
        </section>
    </div>
</div>
{% endif %}

src/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/normalize.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/style.css') }}">
    <title>Geo Draw - Auth</title>
</head>
<body>
    <div class="login">
        <div class="container login__inner">
            <div class="login__box">
                <a href="/oneid/login" class="login__link">
                    <img class="login__img" src="{{ url_for('static', filename='images/login.png') }}" alt="login img" width="220" height="280">
                </a>
            </div>
        </div>
    </div>
</body>
</html>